frontend/controllers/AssessorController.php
<?php

namespace frontend\controllers;

use backend\models\search\LocalitySearch;
use Codeception\Application;
use common\models\ApplicationForm;
use common\models\Assessment;
use common\models\AssessmentConclusion;
use common\models\Issues;
use common\models\Locality;
use common\models\Sop;
use frontend\models\search\ApplicationFormSearch;
use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * LocalityController implements the CRUD actions for Locality model.
 */
class AssessorController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],

            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],

                    [
                        'actions' => ['locality-approve', 'locality-all', 'index', 'create', 'view', 'update', 'delete', 'list-application-form', 'list-issues', 'update-by-issue', 'view-by-issue', 'send-improve', 'send-mail', 'send-notification', 'approve', 'comment'],
                        'allow' => true,
                        'roles' => ['manager', 'director', 'administrator'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Locality models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LocalitySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionLocalityApprove()
    {
        $curDate = date('Y-m-d');
        $fiscalYear = ApplicationForm::fiscalYear($curDate);

        $searchModel = new ApplicationFormSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if (Yii::$app->user->can('director')) {
            $dataProvider->query->andWhere(['province.region_code' => Yii::$app->user->identity->userProfile->office->provinceCode->region_code])->andWhere(['be_year' => $fiscalYear]);
        }

        if (Yii::$app->user->can('manager')) {
            $dataProvider->query->andWhere(['province.province_code' => Yii::$app->user->identity->userProfile->office->province_code])->andWhere(['be_year' => $fiscalYear]);
        }
        
        $dataProvider->pagination->pageSize=100;

        return $this->render('locality-approve', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionLocalityAll()
    {
        $searchModel = new LocalitySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('locality-all', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionListApplicationForm($locality_code)
    {
        $searchModel = new ApplicationFormSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->where(['application_form.locality_code' => $locality_code]);

        return $this->render('list-application-form', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate($application_form_id)
    {
        $appForm = ApplicationForm::find()->joinWith('locality')->joinWith('locality.typeCode')->where(['application_form.id' => $application_form_id])->one();
        $model = ApplicationForm::find()->where(['id' => $application_form_id])->one();

        $assessments = Assessment::getDb()->cache(function ($db) use ($application_form_id) {
            return Assessment::find()->joinWith('sop')->joinWith('sop.issueCode')->joinWith('sop.issueCode.mainIssueCode')->where(['assessment.application_form_id' => $application_form_id])->all(); // ดึงข้อมูล Assessment
        });

        foreach ($assessments as $key => $assessment) {
            $models[] = new Assessment([
                'main_issue_code' => $assessment['sop']['issueCode']['main_issue_code'],
                'main_issue_desc' => $assessment['sop']['issueCode']['mainIssueCode']['main_issue_desc'],
                'issue_code' => $assessment['sop']['issue_code'],
                'issue_desc' => $assessment['sop']['issueCode']['issue_desc'],
                'id' => $assessment['id'],
                'sop_id' => $assessment['sop']['id'],
                'sop_assess_step_detail' => $assessment['sop']['assess_step_detail'],
                'assess_step_evidence' => $assessment['sop']['assess_step_evidence'],
                'selfassess_score' => $assessment['selfassess_score'],
                'selfassess_date' => $assessment['selfassess_date'],
                'assessor_score' => $assessment['assessor_score'],
                'assessor_date' => $assessment['assessor_date'],
                'assessor_notes' => $assessment['assessor_notes'],
                'locality_code' => Yii::$app->user->identity->userProfile->locality_code,
                'sop_parent_id' => $assessment['sop']['parent_id'],
                'sop_issue_code' => $assessment['sop']['issue_code'],
                'sop_assess_step' => $assessment['sop']['assess_step'],
                'sop_assess_step_detail' => $assessment['sop']['assess_step_detail'],
                'sop_assess_score' => $assessment['sop']['assess_score'],
            ]);
        }

        if (Model::loadMultiple($assessments, Yii::$app->request->post())) {
            foreach ($assessments as $assessment) {
                $assessment->save(false);
                unset($assessment);
            }

            $issues = json_decode($model->apply_issues);
            $this->saveScores($model->id, $model->be_year, 'assessor', $model->locality_code, $issues);
            return $this->redirect(['index', 'application_form_id' => $application_form_id]);
        }

        return $this->render('create', [
            'model' => $model,
            'models' => $models,
            'appForm' => $appForm,
        ]);
    }

    public function actionListIssues($application_form_id)
    {
        if (session_id() == '' || !isset($_SESSION)) {
            session_start();
        }

        if (isset($application_form_id)) {
            $applicationForm = ApplicationForm::find()->joinWith('locality')->where(['application_form.id' => $application_form_id])->one();
            if ($applicationForm != null) {
                $apply_issues = Json::decode($applicationForm->apply_issues);
                $apply_issues = is_array($apply_issues) ? $apply_issues : [];
                Yii::$app->session['applicationForm'] = [
                    'applicationForm' => $applicationForm,
                    'application_form_id' => $applicationForm->id,
                    'be_year' => $applicationForm->be_year,
                    'apply_issues' => $apply_issues,
                    'locality_code' => $applicationForm->locality_code,
                    'status' => $applicationForm->status,
                    'locality_name' => $applicationForm->locality->locality_name,
                    'email' => $applicationForm->contact_email
                ];
            } else {
                Yii::$app->session['applicationForm'] = [
                    'application_form_id' => '',
                    'be_year' => '',
                    'apply_issues' => [],
                    'locality_code' => '',
                    'status' => 0,
                    'locality_name' => '',
                    'email' => ''
                ];
            }
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        $query = Issues::find()->where(['IN', 'issues.issue_code', Yii::$app->session['applicationForm']['apply_issues']]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,

            ],
        ]);

        return $this->render('list-issues', [
            'applicationForm' => $applicationForm,
            'dataProvider' => $dataProvider,
            'application_form_id' => Yii::$app->session['applicationForm']['application_form_id'],
        ]);
    }

    public function actionUpdateByIssue($issue_code)
    {
        $models = [];
        $model = ApplicationForm::find()->where(['id' => Yii::$app->session['applicationForm']['application_form_id']])->one();
        $mainSops = Sop::find()->joinWith('issueCode')->joinWith('issueCode.mainIssueCode')->where(['issues.issue_code' => $issue_code])->orderBy(['sop.id' => SORT_ASC])->all();

        $assessments = Assessment::getDb()->cache(function ($db) use ($issue_code) {
            return Assessment::find()->joinWith('sop')->joinWith('sop.issueCode')->joinWith('sop.issueCode.mainIssueCode')->where(['assessment.application_form_id' => Yii::$app->session['applicationForm']['application_form_id']])->andWhere(['sop.issue_code' => $issue_code])->orderBy(['sop.id' => SORT_ASC])->all(); // ดึงข้อมูล Assessment
        });

        if (Model::loadMultiple($assessments, Yii::$app->request->post())) {

frontend/views/assessor/_approve.php
<?php

use trntv\filekit\widget\Upload;
use trntv\yii\datetime\DateTimeWidget;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/**
 * @var $this       yii\web\View
 * @var $model      common\models\Article
 * @var $categories common\models\ArticleCategory[]
 */

?>

<?php $form = ActiveForm::begin([
]) ?>

<?php echo $form->field($model, 'approve')->checkbox(['Yes' => 'ตกลง'], ['maxlength' => true]) ?>


<div class="form-group">
    <?php echo Html::submitButton(
        $model->isNewRecord ? Yii::t('backend', 'บันทึกข้อมูล') : Yii::t('backend', 'บันทึกข้อมูล'),
        ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
</div>

<?php ActiveForm::end() ?>

frontend/views/assessor/_comment-form.php
<?php

use common\models\Sop;
use yii\helpers\VarDumper;
?>

<?php $sop = Sop::find()->where(['id' => $model->sop_id])->one()?>
<h4>ข้อเสนอแนะ: <?php echo !empty($sop->assess_step_evidence) ?  $sop->assess_step_evidence : ''?></h4>
<?php echo \yii2mod\comments\widgets\Comment::widget([
    'model' => $model,
    'commentView' => '@frontend/views/comments/index',
    'dataProviderConfig' => [
        'pagination' => [
            'pageSize' => 10
        ],
    ]
]); ?>

frontend/views/assessor/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Assessment */

$this->title = Yii::t('common', '{modelClass}', [
    'modelClass' => 'ประเมินด้วยผู้ประเมิน',
]);
//$this->params['breadcrumbs'][] = ['label' => Yii::t('common', 'Assessments'), 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->locality_code, 'url' => ['view', 'locality_code' => $model->locality_code, 'sop_id' => $model->sop_id]];
//$this->params['breadcrumbs'][] = Yii::t('common', 'Update');
//

$this->params['breadcrumbs'][] = ['label' => 'ประเมินโดยคณะกรรมการ', 'url' => ['assessor/locality-approve']];
$this->params['breadcrumbs'][] = ['label' => 'รายการประเมิน', 'url' => ['assessor/list-application-form']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="card">
    <div class="card-body">
        <h4 class="card-title"><?php echo $this->title; ?></h4>

        <p class="card-description">

        </p>

        <div class="assessment-update">

            <?php echo $this->render('_form', [
                'models' => $models,
                'model' => $model,
                'appForm' => $appForm,
            ]) ?>
        </div>
    </div>
</div>

frontend/views/assessor/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\LocalitySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('common', 'รายชื่อผู้เขารับการประเมิน');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="card">
    <div class="card-body">
        <h4 class="card-title"><?php echo $this->title; ?></h4>

        <p class="card-description">

        </p>

        <div class="locality-index">

            <?php Pjax::begin(); ?>
            <?php // echo $this->render('_search', ['model' => $searchModel]); ?>


            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

//            'id',
                    'locality_code',
                    'locality_name',
                    'administrator',
                    //'administrative_title',
                    //'type_code',
                    //'address',
                    //'subdistrict_code',
                    //'district_code',
                    //'province_code',
                    //'postal_code',
                    //'active_status',
                    //'created_by_ip',
                    //'created_by',
                    //'created_at',
                    //'updated_by_ip',
                    //'updated_by',
                    //'updated_at',
                    [
                        'label' => 'รับการประเมิน',
                        'format' => 'raw',
                        'value' => function ($data) {
                            return Html::a('รับการประเมิน', ['/assessor/list-application-form', 'locality_code' => $data->locality_code], ['class' => 'btn btn-primary btn-block']);
                        }
                    ]
                ],
            ]); ?>
            <?php Pjax::end(); ?>
        </div>
    </div>
</div>

frontend/views/assessor/list-application-form.php
<?php

use kartik\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\search\ApplicationFormSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('common', 'รายการประเมิน');
$this->params['breadcrumbs'][] = ['label' => Yii::t('common', 'ประเมินโดยคณะกรรมการ'), 'url' => ['/assessor/locality-approve']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="card">
    <div class="card-body">
        <h4 class="card-title"><?php echo $this->title . ' ' . $dataProvider->models[0]->locality->locality_name; ?></h4>
        
        <p class="card-description">

        </p>

        <div class="application-form-index">
            <?php Pjax::begin();?>
            <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

            <?=GridView::widget([
                'dataProvider' => $dataProvider,
//                'filterModel' => $searchModel,
                'columns' => [

//                    [
//                        'class' => 'kartik\grid\ExpandRowColumn',
//                        'width' => '50px',
//                        'value' => function ($model, $key, $index, $column) {
//                            return GridView::ROW_EXPANDED;
//                        },
//                        'detail' => function ($data, $key, $index, $column) {
//
//                            $apply_issues = \yii\helpers\Json::decode($data->apply_issues);
//                            $apply_issues = is_array($apply_issues) ? $apply_issues : [];
//                            $query = \common\models\Issues::find()->where(['IN', 'issues.issue_code', $apply_issues]);
//
//                            $dataProvider = new \yii\data\ActiveDataProvider([
//                                'query' => $query,
//                                'pagination' => [
//                                    'pageSize' => 20,
//
//                                ],
//                            ]);
//                            return Yii::$app->controller->renderPartial('/assessor/list-issues', [
//                                'dataProvider' => $dataProvider,
//                                'application_form_id' => $data->id
//                            ]);
//                        },
//                        'headerOptions' => ['class' => 'kartik-sheet-style'],
//                        'expandOneOnly' => true,
//                    ],

                    'be_year',
                    [
                        'label' => 'อปท.',
                        'value' => function ($data) {
                            return  '['.$data->locality_code .'] '.$data->locality->locality_name;
                        },
                    ],

//                    'contact_person',
                    //                    'contact_title',

                    //'contact_mobile',
                    //'contact_email:email',
                    //'apply_person',
                    //'apply_title',
                    //'apply_issues:ntext',
                    //'apply_date',
                    //'created_by_ip',
                    //'created_by',
//                    [
//                        'label' => 'วันที่สร้าง',
//                        'attribute' => 'created_at',
//                        'value' => function($data){
//                            return Yii::$app->formatter->asDate($data->created_at, 'dd MMMM Y');
//                        }
//                    ],
                    //'updated_by_ip',
                    //'updated_by',
                    //'updated_at',
//                    [
//                        'label' => 'สถานะ',
//                        'format' => 'raw',
//                        'value' => function ($data) {
//                            $model = \common\models\AssessmentResult::findOne($data->status);
//                            return $model !== null ? $model->result_desc : 'เตรียมข้อมูล';
//                        },
//                    ],

                    [
                        'label' => 'รายการ',
                        'format' => 'raw',
                        'value' => function ($data) {
                            if ($data->status > 0) {
                                return Html::a('รายการประเด็น', ['assessor/list-issues', 'application_form_id' => $data->id], [
                                    'class' => 'btn btn-info btn-fw btn-xs',
                                    'data-pjax' => '0',
                                    //'disabled' => $data->status == 2 ? false : 'disabled'
                                    ]);

//                                . ' ' . Html::a('แสดงการประเมิน', ['assessment/index', 'be_year' => $data->be_year, 'application_form_id' => $data->id], [
//                                    'class' => 'btn btn-success btn-fw btn-sm',
//                                    'data-pjax' => '0',
//                                ]);
                            }
                        },
                    ],
                ],
            ]);?>
            <?php Pjax::end();?>
        </div>
    </div>
</div>

frontend/views/assessor/locality-approve.php
<?php

use common\models\ApplicationForm;
use yii\widgets\Pjax;
use common\models\District;
use common\models\Locality;
use common\models\Province;
use kartik\select2\Select2;
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\LocalitySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('common', 'ประเมินโดยคณะกรรมการ');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">รายชื่อ อปท. เข้ารับการประเมิน</h4>
        <div class="locality-index">
            <?php Pjax::begin(); ?>
            <?php // echo $this->render('_search', ['model' => $searchModel]); 
            ?>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    [
                        'attribute' => 'locality_code',
                        'label' => 'อปท.',
                        'vAlign' => 'middle',
                        'width' => '180px',
                        'value' => function ($data) {
                            return $data->locality->locality_name;
                        },
                        'filterType' => GridView::FILTER_SELECT2,
                        'filterWidgetOptions' => [
                            'size' => Select2::LARGE,
                            'data' => yii\helpers\ArrayHelper::map(Locality::find()->all(), 'locality_code', 'locality_name'),
                            'pluginOptions' => [
                                'allowClear' => true,
                                'ajax' => [
                                    'url' => Url::to(['/user/default/local-list']),
                                    'dataType' => 'json',
                                    'data' => new JsExpression('function(params) { return {q:params.term};}')
                                ],

                                'escapeMarkup' => new JsExpression('function(markup) { return markup;}'),
                                'templateResult' => new JsExpression('function(local){ return local.text;}'),
                                'templateSelection' => new JsExpression('function(local) {return local.text;}'),
                            ],
                        ],
                        'filterInputOptions' => ['placeholder' => '-- อปท. --'],
                        'format' => 'raw'
                    ],

                    [
                        'attribute' => 'district',
                        'label' => 'อำเภอ',
                        'vAlign' => 'middle',
                        'width' => '180px',
                        'value' => function ($data) {
                            return $data->locality->districtCode->district_name;
                        },
                        'filterType' => GridView::FILTER_SELECT2,
                        'filterWidgetOptions' => [
                            'size' => Select2::LARGE,
                            'data' => yii\helpers\ArrayHelper::map(District::find()->all(), 'district_code', 'district_name'),
                            'pluginOptions' => [
                                'allowClear' => true,
                                'ajax' => [
                                    'url' => Url::to(['/user/default/district-list']),
                                    'dataType' => 'json',
                                    'data' => new JsExpression('function(params) { return {q:params.term};}')
                                ],

                                'escapeMarkup' => new JsExpression('function(markup) { return markup;}'),
                                'templateResult' => new JsExpression('function(district){ return district.text;}'),
                                'templateSelection' => new JsExpression('function(district) {return district.text;}'),
                            ],
                        ],
                        'filterInputOptions' => ['placeholder' => '-- อำเภอ --'],
                        'format' => 'raw'
                    ],

                    [
                        'attribute' => 'province',
                        'label' => 'จังหวัด',
                        'value' => function ($data) {
                            return $data->locality->provinceCode->province_name;
                        },
                        'filterType' => GridView::FILTER_SELECT2,
                        'filterWidgetOptions' => [
                            'size' => Select2::LARGE,
                            'data' => yii\helpers\ArrayHelper::map(Province::find()->all(), 'province_code', 'province_name'),
                            'pluginOptions' => [
                                'allowClear' => true,
                            ],
                        ],
                        'filterInputOptions' => ['placeholder' => '-- จังหวัด --'],
                        'format' => 'raw'
                    ],

                    [
                        'attribute' => 'be_year',
                        // 'filter'=>ArrayHelper::map(ApplicationForm::find()->groupBy('be_year')->asArray()->all(), 'be_year', 'be_year'),
                        'filter' => Select2::widget([
                            'model' => $searchModel,
                            'attribute' => 'be_year',
                            'value' => $searchModel->be_year,
                            'data' => ArrayHelper::map(ApplicationForm::find()->asArray()->all(), 'be_year', 'be_year'),
                            'size' => Select2::LARGE,
                            'options' => [
                                'placeholder' => '-- ปีงบประมาณ --',
                                'style' => 'width: 10%;'
                            ],
                            'pluginOptions' => [
                                'allowClear' => true
                            ],
                            // 'addon' => [
                            //     'prepend' => [
                            //         'content' => FAS::icon('open')
                            //     ]
                            // ],
                        ]),
                    ],

                    // [
                    //     'attribute' => 'province',
                    //     'label' => 'จังหวัด',
                    //     'value' => function ($data) {
                    //         return $data->provinceCode->province_name;
                    //     },
                    //     'filter' => Select2::widget([
                    //         'name' => 'LocalitySearch[province]',
                    //         'model' => $searchModel,
                    //         'value' => $searchModel->province_code,
                    //         'data' =>  \yii\helpers\ArrayHelper::map(\common\models\Province::find()->asArray()->all(), 'province_code', 'province_name'),
                    //         // 'data' => function () {
                    //         //     if (Yii::$app->user->can('webmaster')) {
                    //         //         return \yii\helpers\ArrayHelper::map(\common\models\Province::find()->asArray()->all(), 'province_code', 'province_name');
                    //         //     }
                    //         //     if (Yii::$app->user->can('manager')) {
                    //         //         return \yii\helpers\ArrayHelper::map(\common\models\Province::find()->where(['province_code' => isset(Yii::$app->user->identity->userProfile->office->province_code) ? Yii::$app->user->identity->userProfile->office->province_code : ''])->asArray()->all(), 'province_code', 'province_name');
                    //         //     }
                    //         // },
                    //         'size' => Select2::LARGE,
                    //         'options' => [
                    //             'placeholder' => '-- จังหวัด --',
                    //             'style' => 'width: 100%;'
                    //         ],
                    //         'pluginOptions' => [
                    //             'allowClear' => true
                    //         ],
                    //         // 'addon' => [
                    //         //     'prepend' => [
                    //         //         'content' => FAS::icon('open')
                    //         //     ]
                    //         // ],
                    //     ]),
                    // ],

                    //'administrative_title',
                    //'type_code',
                    //'address',
                    //'subdistrict_code',
                    //'district_code',
                    //'province_code',
                    //'postal_code',
                    //'active_status',
                    //'created_by_ip',
                    //'created_by',
                    //'created_at',
                    //'updated_by_ip',
                    //'updated_by',
                    //'updated_at',
                    [
                        'label' => 'รับการประเมิน',
                        'format' => 'raw',
                        'value' => function ($data) {
                            return Html::a('<i class="icon-list"></i> รับการประเมิน', ['/assessor/list-issues', 'application_form_id' => $data->id], ['class' => 'btn btn-primary btn-block btn-xs']);
                            // return Html::a('<i class="icon-list"></i> รับการประเมิน', ['/assessor/list-application-form', 'locality_code' => $data->locality_code], ['class' => 'btn btn-primary btn-block btn-xs']);
                        }
                    ],
                ]
            ]); ?>
            <?php Pjax::end(); ?>
        </div>
    </div>
</div>