frontend/controllers/ApplicationFormController.php
<?php

namespace frontend\controllers;

use common\models\Assessment;
use common\models\Locality;
use common\models\Sop;
use common\models\User;
use Yii;
use common\models\ApplicationForm;
use common\models\AssessmentConclusion;
use frontend\models\search\ApplicationFormSearch;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\MainIssues;
use common\models\Issues;
use yii\db\Expression;

/**
 * ApplicationFormController implements the CRUD actions for ApplicationForm model.
 */
class ApplicationFormController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [

            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'create', 'update', 'view', 'index', 'submit-app-form', 'list-application-form', 'index',
                            'list-send-app-form', 'delete-assessment'
                        ],
                        'allow' => true,
                        'roles' => ['user', 'administrator'],
                        'denyCallback' => function () {
                            return Yii::$app->controller->redirect(['/user/default/index']);
                        }
                    ],
                ]
            ],

            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],

        ];
    }

    public function actionIndex()
    {
        $applicationForm = ApplicationForm::find()->where(['locality_code' => Yii::$app->user->identity->userProfile->locality_code])->one();
        return $this->render('index', [
            'applicationForm' => $applicationForm,
        ]);
    }

    /**
     * Lists all ApplicationForm models.
     * @return mixed
     */
    public function actionListApplicationForm()
    {
        unset(Yii::$app->session['applicationForm']);

        $searchModel = new ApplicationFormSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->where(['locality.locality_code' => Yii::$app->user->identity->userProfile->locality_code]);

        return $this->render('list-application-form', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ApplicationForm model.
     * @param integer $be_year
     * @param string $locality_code
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($be_year, $locality_code)
    {
        return $this->render('view', [
            'model' => $this->findModel($be_year, $locality_code),
        ]);
    }


    /**
     * Creates a new ApplicationForm model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new ApplicationForm();
        $localInfo = Locality::find()->joinWith('typeCode')->joinWith('subdistrictCode')->joinWith('districtCode')->joinWith('provinceCode')->where(['locality.locality_code' => Yii::$app->user->identity->userProfile->locality_code])->one();
        $Issues = Issues::find()->with('mainIssueCode');

        $model->be_year = ApplicationForm::fiscalYear(date('Y-m-d'));
   
        //localityInfo
        $model->localityType = !empty($localInfo->typeCode->type_name) ? $localInfo->typeCode->type_name : '';
        $model->localityName = !empty($localInfo->locality_name) ? $localInfo->locality_name : '';
        $model->subdictrict = !empty($localInfo->subdistrictCode->subdistrict_name) ? $localInfo->subdistrictCode->subdistrict_name : '';
        $model->dictrict = !empty($localInfo->districtCode->district_name) ? $localInfo->districtCode->district_name : '';
        $model->province = !empty($localInfo->provinceCode->province_name) ? $localInfo->provinceCode->province_name : '';
        $model->tel = !empty(Yii::$app->user->identity->userProfile->phone) ? Yii::$app->user->identity->userProfile->phone : '';
        $model->directorName = !empty($localInfo->typeCode->administrator) ? $localInfo->typeCode->administrator : '';
        $model->position = !empty($localInfo->typeCode->office) ? $localInfo->typeCode->office : '';

        $model->locality_code = Yii::$app->user->identity->userProfile->locality_code;
        $model->contact_person = Yii::$app->user->identity->getPublicIdentity();
        $model->contact_phone = Yii::$app->user->identity->userProfile->phone;
        $model->contact_mobile = Yii::$app->user->identity->userProfile->mobile;
        $model->contact_email = Yii::$app->user->identity->email;


        if ($model->load(Yii::$app->request->post())) {

            if (Yii::$app->request->post('selection')) {
                $selects = Yii::$app->request->post('selection');
                $model->apply_issues = Json::encode($selects);
                $model->status = 1;
                if ($model->save()) {

                    Yii::$app->getSession()->setFlash('alert', [
                        'body' => 'เลือกประเด็นการขอรับการประเมินเรียบร้อยแล้ว',
                        'options' => ['class' => 'alert alert-success', 'role' => 'alert']
                    ]);

                    return $this->redirect(['list-application-form']);
                }
            }
        }

        $dataProvider = new ActiveDataProvider([
            'query' => $Issues,
        ]);

        return $this->render('create', [
            'model' => $model,
            'localInfo' => $localInfo,
            'selection' => [],
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Updates an existing ApplicationForm model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $be_year
     * @param string $locality_code
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($be_year, $locality_code)
    {

        $model = ApplicationForm::find()->where(['be_year' => $be_year, 'locality_code' => $locality_code])->one();

        $Issues = Issues::find()->with('mainIssueCode');
        $localInfo = Locality::find()->joinWith('typeCode')->joinWith('subdistrictCode')->joinWith('districtCode')->joinWith('provinceCode')->where(['locality.locality_code' => Yii::$app->user->identity->userProfile->locality_code])->one();

        if ($model !== null) {
            $selection = isset($model->apply_issues) ? Json::decode($model->apply_issues) : [];

            //localityInfo
            $model->localityType = !empty($localInfo->typeCode->type_name) ? $localInfo->typeCode->type_name : '';
            $model->localityName = !empty($localInfo->locality_name) ? $localInfo->locality_name : '';
            $model->subdictrict = !empty($localInfo->subdistrictCode->subdistrict_name) ? $localInfo->subdistrictCode->subdistrict_name : '';
            $model->dictrict = !empty($localInfo->districtCode->district_name) ? $localInfo->districtCode->district_name : '';
            $model->province = !empty($localInfo->provinceCode->province_name) ? $localInfo->provinceCode->province_name : '';
            $model->tel = !empty(Yii::$app->user->identity->userProfile->phone) ? Yii::$app->user->identity->userProfile->phone : '';
            $model->directorName = !empty($localInfo->typeCode->administrator) ? $localInfo->typeCode->administrator : '';
            $model->position = !empty($localInfo->typeCode->office) ? $localInfo->typeCode->office : '';

            $dataProvider = new ActiveDataProvider([
                'query' => $Issues,
            ]);

            if ($model === null) {
                $selection = isset($model->apply_issues) ? Json::decode($model->apply_issues) : [];

                //localityInfo
                $model->localityType = !empty($localInfo->typeCode->type_name) ? $localInfo->typeCode->type_name : '';
                $model->localityName = !empty($localInfo->locality_name) ? $localInfo->locality_name : '';
                $model->subdictrict = !empty($localInfo->subdistrictCode->subdistrict_name) ? $localInfo->subdistrictCode->subdistrict_name : '';
                $model->dictrict = !empty($localInfo->districtCode->district_name) ? $localInfo->districtCode->district_name : '';
                $model->province = !empty($localInfo->provinceCode->province_name) ? $localInfo->provinceCode->province_name : '';
                $model->tel = !empty(Yii::$app->user->identity->userProfile->phone) ? Yii::$app->user->identity->userProfile->phone : '';
                $model->directorName = !empty($localInfo->typeCode->administrator) ? $localInfo->typeCode->administrator : '';
                $model->position = !empty($localInfo->typeCode->office) ? $localInfo->typeCode->office : '';

                $dataProvider = new ActiveDataProvider([
                    'query' => $Issues,
                ]);
            }

            if ($model->load(Yii::$app->request->post())) {

                $selects = Yii::$app->request->post('selection');

                $arDels = [];
                $ar1 = Json::decode($model->apply_issues);
                $ar2 = Yii::$app->request->post('selection');

                foreach ($ar1 as $item) {
                    if (in_array($item, $ar2)) {
                    } else {
                        $arDels[] = $item;

frontend/views/application-form/_form.php
<?php

use backend\models\LpaScore;
use common\models\ApplicationForm;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $model common\models\ApplicationForm */
/* @var $form yii\widgets\ActiveForm */
?>


<div class="application-form-form">

    <?php $form = ActiveForm::begin([
        'encodeErrorSummary' => false,
    ]); ?>

    <!-- <div class="row">
        <div class="col-md-10"> -->
            <?= $form->errorSummary($model, ['class' => 'alert alert-danger']); ?>
        <!-- </div>
        <div class="col-md-2"> -->
            <?php //echo Html::a('<i class="icon-pencil"></i> แก้ไขประเด็น',  \yii\helpers\Url::to(['/application-form/update', 'be_year' => $model->be_year, 'locality_code' => $model->locality_code]), ['class' => 'btn btn-warning  btn-block']); ?>
        <!-- </div>
    </div> -->

    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'localityType')->textInput(['readonly' => true]); ?>
            <?= $form->field($model, 'be_year', ['template' => "{label}\n{input}\n{hint}"])->hiddenInput(['readonly' => true, 'id' => 'be_year'])->label(false) ?>
        </div>
        <div class="col-md-8">
            <?= $form->field($model, 'localityName')->textInput(['readonly' => true]); ?>
            <?= $form->field($model, 'locality_code', ['template' => "{label}\n{input}\n{hint}"])->hiddenInput(['readonly' => true, 'id' => 'locality_code'])->label(false); ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <?= $form->field($model, 'subdictrict')->textInput(['readonly' => true]); ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'dictrict')->textInput(['readonly' => true]); ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'province')->textInput(['readonly' => true]); ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'tel')->textInput(['readonly' => true]); ?>
        </div>
        <div class="col-md-2">
            <?php echo $form->field($model, 'be_year')->textInput(['readonly' => true])->label('LPA Score ปีงบประมาณ'); ?>
            <?php //echo $form->field($model, 'be_year')->dropDownList(ApplicationForm::createRangeYear(date('Y', strtotime('+1 year'))+543))->label('ปีงบประมาณ') ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'apply_person')->textInput([]); ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'apply_title')->textInput([]); ?>
        </div>
    </div>
    <br>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'summary' => '',
        'columns' => [
            [
                'attribute' => 'mainIssueCode.main_issue_code',
                'group' => true,  // enable grouping
            ],
            [
                'attribute' => 'mainIssueCode.main_issue_desc',
                'group' => true,  // enable grouping
            ],
            [
                'class' => '\kartik\grid\CheckboxColumn',
                'header' => Html::checkBox('selection_all', false, [
                    'class' => 'select-on-check-all',
                    'label' => 'เลือกทั้งหมด',
                ]),
                'rowSelectedClass' => GridView::TYPE_INFO,
                'checkboxOptions' => function ($data, $key, $index, $column) use ($selection, $model) {
                    $assessmentConclusion = \common\models\AssessmentConclusion::find()->where(['issue_code' => $data->issue_code])->andWhere(['be_year' => $model->be_year])->andWhere(['type' => 'selfassess'])->andWhere(['approve' => 'Sent'])->andWhere(['locality_code' => Yii::$app->user->identity->userProfile->locality_code])->one();
                    $bool = $selection != null ? in_array($data->issue_code, $selection) : false;
                    return [
                        'value' => $data->issue_code,
                        'checked' => $bool,
                        // 'disabled' => $assessmentConclusion != null ? 'disabled' : false,
                    ];
                },

            ],
            [
                'attribute' => 'issue_desc',
                'value' => function ($data) {
                    return $data->issue_name . " " . $data->issue_desc;
                }
            ],
        ],
    ]); ?>

    <br>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'contact_person')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'contact_title')->textInput(['maxlength' => true]) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <?= $form->field($model, 'contact_phone')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'contact_mobile')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'contact_email')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <hr>
    <div class="form-group">
        <p>
            <?php echo Html::submitButton('<i class="glyphicon glyphicon-save"></i> บันทึกข้อมูล', ['class' => 'btn btn-primary', $model->status <= 1 ? 'disabled' == false : 'disabled' => true]); ?>
            <?php echo $model->isNewRecord ? Html::button('<i class="glyphicon glyphicon-print"></i> พิมพ์ใบสมัคร', ['class' => 'btn btn-default', 'disabled' => true]) : Html::a('<i class="glyphicon glyphicon-print"></i> พิมพ์ใบสมัคร', ['/documents/print-appform', 'be_year' => $model->be_year, 'locality_code' => Yii::$app->user->identity->userProfile->locality_code], ['class' => 'btn btn-success', 'target' => '_blank']) ?>
        </p>
    </div>
    <?php ActiveForm::end(); ?>

</div>

<div id="url-get-unactive" data-ungetactive="<?php echo \yii\helpers\Url::to(['application-form/delete-assessment']) ?>"></div>


<?php
$js = <<< JS


    // $('.kv-row-checkbox').change(function() {
    //     if(this.checked) {
    //          $(this).prop("checked", true);
    //     }else{
    //         var issue_code = $(this).val();
    //         var be_year = $('#be_year').val();
    //         var locality_code = $('#locality_code').val();
    //         var url = $('#url-get-unactive').data('ungetactive');
    //         if (confirm('ผมประเมินของประเด็นนี้จะถูกลบทั้งหมด คุณต้องการลบข้อมูล ใช่ หรือ ไม่')) {
    //         $.ajax({
    //             url: url,
    //             type: 'POST',
    //             dataType: 'JSON',
    //             data: {issue_code: issue_code, be_year: be_year, locality_code: locality_code}
    //         }).done(function (data){
    //             $(this).prop("checked", false);
    //             });
    //         }
    //         else{
    //          $(this).prop("checked", true);
    //         }
    //     }
    // });

JS;
$this->registerJS($js);
?>

frontend/views/application-form/index.php
<?php
/**
 * Created by PhpStorm.
 * User: pil2ate
 * Date: 8/11/18 AD
 * Time: 11:32
 */

$this->title = 'การประเมิน EHA';
//$this->params['breadcrumbs'][] = ['label' => '', 'url' => ['']];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="row">
    <div class="col-md-6 grid-margin">
        <div class="card">
            <a href="<?php echo \yii\helpers\Url::to(['/user/sign-in/signup']) ?>"
               style="text-decoration: none; color: #000000; disable">
                <div class="card-body">
                    <div class="d-flex align-items-center">
                        <div class="icon-in-bg bg-success text-white rounded-circle">
                            <i class="icon-check font-weight-bold"></i>
                        </div>
                        <div class="ml-4">
                            <h4>ขั้นตอนที่ 1</h4>

                            <h3 class="mb-0 font-weight-medium">ลงทะเบียนเข้าใช้งาน</h3>
                            <small class="text-gray">ดำเนินการแล้ว</small>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-6 grid-margin">
        <div class="card">
            <a href="<?php echo \yii\helpers\Url::to(['/user/default/index']) ?>"
               style="text-decoration: none; color: #000000; disable">
                <div class="card-body">
                    <div class="d-flex align-items-center">
                        <div class="icon-in-bg bg-success text-white rounded-circle">
                            <i class="icon-check font-weight-bold"></i>
                        </div>
                        <div class="ml-4">
                            <h4>ขั้นตอนที่ 2</h4>

                            <h3 class="mb-0 font-weight-medium">ระบุหน่วยงานและข้อมูลการติดต่อ</h3>
                            <small class="text-gray">ดำเนินการแล้ว</small>

                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>

</div>


<div class="row">
    <!-- <div class="col-md-6 grid-margin">
        <div class="card">
            <a href="<?php //echo \yii\helpers\Url::to(['/application-form/create']) ?>"
               style="text-decoration: none; color: #000000; disable">
                <div class="card-body">
                    <div class="d-flex align-items-center">
                        <?php //if (isset($applicationForm->apply_issues) && $applicationForm->apply_issues != null): ?>
                            <div class="icon-in-bg bg-success text-white rounded-circle">
                                <i class="icon-check font-weight-bold"></i>
                            </div>
                        <?php //endif; ?>
                        <?php //if (empty($applicationForm->apply_issues)): ?>
                            <div class="icon-in-bg bg-warning text-white rounded-circle">
                                <i class="icon-close font-weight-bold"></i>
                            </div>
                        <?php //endif; ?>
                        <div class="ml-4">
                            <h4>ขั้นตอนที่ 3</h4>

                            <h3 class="mb-0 font-weight-medium">เลือกประเด็นขอรับการประเมิน</h3>
                            <?php //if (isset($applicationForm->apply_issues) && $applicationForm->apply_issues != null): ?>
                                <small class="text-gray"><?php //echo 'ดำเนินการแล้ว'; ?></small>
                            <?php //endif; ?>
                            <?php //if (empty($applicationForm->apply_issues)): ?>
                                <small class="text-gray"><?php //echo 'ยังไม่ดำเนินการ' ?></small>
                            <?php //endif; ?>

                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div> -->

    <div class="col-md-6 grid-margin">
        <div class="card">
            <a href="<?php echo \yii\helpers\Url::to(['/application-form/list-application-form']) ?>"
               style="text-decoration: none; color: #000000; disable">
                <div class="card-body">
                    <div class="d-flex align-items-center">
                        <?php if (isset($applicationForm)): ?>
                            <div class="icon-in-bg bg-success text-white rounded-circle">
                                <i class="icon-check font-weight-bold"></i>
                            </div>
                        <?php endif; ?>
                        <?php if (!isset($applicationForm)): ?>
                            <div class="icon-in-bg bg-warning text-white rounded-circle">
                                <i class="icon-close font-weight-bold"></i>
                            </div>
                        <?php endif; ?>
                        <div class="ml-4">
                            <h4>ขั้นตอนที่ 3</h4>

                            <h3 class="mb-0 font-weight-medium">เลือกประเด็นขอรับการประเมิน</h3>
                            <?php if ($applicationForm != null): ?>
                                <small class="text-gray"><?php echo 'ดำเนินการแล้ว'; ?></small>
                            <?php endif; ?>
                            <?php if ($applicationForm == null): ?>
                                <small class="text-gray"><?php echo 'ยังไม่ดำเนินการ' ?></small>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-6 grid-margin">
        <div class="card">
            <a href="<?php echo \yii\helpers\Url::to(['/documents/list-issues']) ?>"
               style="text-decoration: none; color: #000000; disable">
                <div class="card-body">
                    <div class="d-flex align-items-center">
                        <?php $ckeckConclusion = \common\models\AssessmentConclusion::find()->where(['locality_code' => Yii::$app->user->identity->userProfile->locality_code])->andWhere(['type' => 'assessor'])->all() ?>
                        <?php if (isset($ckeckConclusion) && $ckeckConclusion != null): ?>
                            <div class="icon-in-bg bg-success text-white rounded-circle">
                                <i class="icon-check font-weight-bold"></i>
                            </div>
                        <?php endif; ?>
                        <?php if ($ckeckConclusion == null): ?>
                            <div class="icon-in-bg bg-warning text-white rounded-circle">
                                <i class="icon-close font-weight-bold"></i>
                            </div>
                        <?php endif; ?>
                        <div class="ml-4">
                            <h4>ขั้นตอนที่ 4</h4>

                            <h3 class="mb-0 font-weight-medium">สรุปผลการประเมิน (จากคณะกรรมการ)</h3>
                            <?php if (isset($ckeckConclusion) && $ckeckConclusion != null): ?>
                                <small class="text-gray"><?php echo 'ดำเนินการแล้ว'; ?></small>
                            <?php endif; ?>
                            <?php if ($ckeckConclusion == null): ?>
                                <small class="text-gray"><?php echo 'ยังไม่ดำเนินการ' ?></small>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>

</div>

frontend/views/application-form/list-application-form.php
<?php

use kartik\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\search\ApplicationFormSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('common', 'ประเมินตนเอง');
$this->params['breadcrumbs'][] = ['label' => Yii::t('common', 'ประเมิน EHA'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="application-form-index">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title"><?php echo $this->title; ?></h4>

            <?= \common\widgets\ApplicationFormDetail::widget(); ?>

            <div class="row">
                <div class="col-md-12">
                    <p><?php echo Html::a('<i class="icon-plus"></i> สมัครเพิ่มประเด็น',  \yii\helpers\Url::to(['/application-form/create']), ['class' => 'btn btn-primary btn-md pull-right']) ?></p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'pjax' => false,
                        'columns' => [
                            //                    [
                            //                        'class' => 'kartik\grid\ExpandRowColumn',
                            //                        'width' => '50px',
                            //                        'value' => function ($model, $key, $index, $column) {
                            //                            return GridView::ROW_EXPANDED;
                            //                        },
                            //                        'detail' => function ($data, $key, $index, $column) {
                            //
                            //                            $apply_issues = \yii\helpers\Json::decode($data->apply_issues);
                            //                            $apply_issues = is_array($apply_issues) ? $apply_issues : [];
                            //                            $query = \common\models\Issues::find()->where(['IN', 'issues.issue_code', $apply_issues]);
                            //
                            //                            $dataProvider = new \yii\data\ActiveDataProvider([
                            //                                'query' => $query,
                            //                                'pagination' => [
                            //                                    'pageSize' => 20,
                            //
                            //                                ],
                            //                            ]);
                            //                            return Yii::$app->controller->renderPartial('/assessment/list-issues', [
                            //                                'dataProvider' => $dataProvider,
                            //                                'application_form_id' => $data->id
                            //                            ]);
                            //                        },
                            //                        'headerOptions' => ['class' => 'kartik-sheet-style'],
                            //                        'expandOneOnly' => true,
                            //                    ],
                            [
                                'attribute' => 'be_year',
                                'label' => 'ปีงบประมาณ',
                            ],
                            [
                                'label' => 'ชื่อ อปท.',
                                'value' => function ($data) {
                                    return '[' . $data->locality_code . ' ] ' . $data->locality->locality_name;
                                },
                            ],
                            [
                                // 'label' => 'รายการประเด็น',
                                'format' => 'raw',
                                'value' => function ($data) {
                                    return Html::a('<i class="icon-list"></i> ประเมินตนเองรายการประเด็น', ['/assessment/list-issues', 'application_form_id' => $data->id], ['class' => 'btn btn-block btn-xs btn-primary']);
                                }
                            ],

                            [
                                // 'label' => 'แก้ไข',
                                'format' => 'raw',
                                'options' => ['style' => 'width:140px;'],
                                'value' => function ($data) {
                                    return Html::a('<i class="icon-pencil"></i> แก้ไขประเด็น',  \yii\helpers\Url::to(['/application-form/update', 'be_year' => $data->be_year, 'locality_code' => $data->locality_code]), ['class' => 'btn btn-warning btn-xs btn-block']);
                                }
                            ],

                            [
                                // 'label' => 'พิมพ์ใบสรุป',
                                'format' => 'raw',
                                'options' => ['style' => 'width:150px;'],
                                'value' => function ($data) {
                                    return Html::a('<i class="icon-printer"></i> พิมพ์ใบสรุป', ['/documents/print-assessment', 'application_form_id' => $data->id], ['class' => 'btn btn-xs btn-block btn-success btn-block', 'target' => '_blank']);
                                }
                            ],
                            //                    [
                            //                        'label' => 'คะแนนประเมินตนเอง',
                            //                        'value' => function($data){
                            //                            return '0';
                            //                        }
                            //                    ],
                            //                    [
                            //                        'label' => 'คะแนนประเมินจากกรรมการ',
                            //                        'value' => function($data){
                            //                            return '0';
                            //                        }
                            //                    ],
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>